### ISSUE TITLE
the program will crash when tiff button is pushed

### ISSUE THREAD

**Issue by 3togo** [AbsurdePhoton/superpixels-segmentation-gui-opencv#2]
it will crashed with segmentation fault
[New Thread 0x7fffba3ed640 (LWP 128682)]
[Thread 0x7fffba3ed640 (LWP 128682) exited]
xxx

Thread 1 "superpixels-seg" received signal SIGSEGV, Segmentation fault.
0x00007ffff7b4dab5 in ParseGeometry (geometry=0x12c <error: Cannot access memory at address 0x12c>, geometry_info=0x7fffffffc130) at MagickCore/geometry.c:886
886	  if ((geometry == (char *) NULL) || (*geometry == '\0'))

**Comment by AbsurdePhoton** [comment]
Mmmh do you have Image Magick 7 ? This is the version I'm using.
